// ---- shared helpers (generated by Design System Definer; reads CONFIG above) ----
const _page = figma.root.children.find(p => p.id === PAGE_ID);
if (!_page) return {error: 'PAGE_ID not found in this file: ' + PAGE_ID};
await figma.setCurrentPageAsync(_page);
const APPLY = typeof APPLY_FLAG === 'undefined' ? true : APPLY_FLAG;
const bump = (o, k, n = 1) => { o[k] = (o[k] || 0) + n; };
const VISIBLE = n => n.visible !== false;
const absT = n => ({x: n.absoluteTransform[0][2], y: n.absoluteTransform[1][2]});
// walk a frame; never descend into instances (they come from other libraries or components)
const walk = (n, out, inInst) => { out.push([n, inInst]); if ('children' in n) { const ni = inInst || n.type === 'INSTANCE'; for (const c of n.children) { if (!VISIBLE(c)) continue; walk(c, out, ni); } } };
const collect = async ids => { const out = []; for (const id of ids) { const r = await figma.getNodeByIdAsync(id); walk(r, out, false); } return out; };
const cols = await figma.variables.getLocalVariableCollectionsAsync();
const cn = {}; for (const c of cols) cn[c.id] = c.name;
const allV = await figma.variables.getLocalVariablesAsync();
const V = {}, byId = {};
for (const v of allV) { V[cn[v.variableCollectionId] + '::' + v.name] = v; byId[v.id] = v; }
const resolveVal = v => { let x = v.valuesByMode[Object.keys(v.valuesByMode)[0]], g = 0; while (x && x.type === 'VARIABLE_ALIAS' && g++ < 9) { const t = byId[x.id]; x = t.valuesByMode[Object.keys(t.valuesByMode)[0]]; } return x; };
const toHex = c => '#' + [c.r, c.g, c.b].map(x => Math.round(x * 255).toString(16).padStart(2, '0')).join('');
const lab = c => { const f = u => u <= 0.04045 ? u / 12.92 : Math.pow((u + 0.055) / 1.055, 2.4); const r = f(c.r), g = f(c.g), b = f(c.b);
  const x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047, y = 0.2126 * r + 0.7152 * g + 0.0722 * b, z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883;
  const h = t => t > 0.008856 ? Math.cbrt(t) : 7.787 * t + 16 / 116; const fx = h(x), fy = h(y), fz = h(z); return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)]; };
const dE = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
const chroma = l => Math.hypot(l[1], l[2]);
// ---- colour candidates, built from the tokens the skill generated ----
const steps = CONFIG.steps;
const ramp = p => steps.map(s => CONFIG.primitives + '::' + p + '/' + s);
const NEUT = CONFIG.ramps.neutral.flatMap(ramp), GRN = CONFIG.ramps.brand.flatMap(ramp), STAT = CONFIG.ramps.status.flatMap(ramp);
const cand = keys => keys.filter(k => V[k]).map(k => ({k, lab: lab(resolveVal(V[k])), sem: !k.startsWith(CONFIG.primitives + '::')}));
const C_FILL = cand([...CONFIG.roles.surface, ...NEUT, ...GRN, ...STAT]);
const C_ICON = cand([...CONFIG.roles.text, ...CONFIG.roles.surface, ...NEUT, ...GRN, ...STAT]);
const C_STROKE = cand([...CONFIG.roles.border, ...NEUT, ...GRN, ...STAT]);
const ACTION = CONFIG.roles.actionDefault;
const pickColor = (c, list, hint) => { const L = lab(c), ch = chroma(L); let best = null;
  for (const x of list) { const raw = dE(L, x.lab); let d = raw - (x.sem ? 4 : 0);
    if (x.k === ACTION) d += (hint === 'button' ? -1 : 1);
    if (!best || d < best.d) best = {k: x.k, d, raw}; }
  return best && best.raw <= (ch < 10 ? 16 : 12) ? best : null; };
// background behind a layer: nearest filled sibling below it, else ancestors; gradients are averaged
const solidOf = n => { if (!('fills' in n) || !Array.isArray(n.fills)) return null;
  for (const p of n.fills) { if (p.visible === false) continue;
    if (p.type === 'SOLID' && (p.opacity === undefined || p.opacity >= 0.85)) return p.color;
    if (p.type === 'IMAGE') return 'img';
    if (p.type.startsWith('GRADIENT') && p.gradientStops && p.gradientStops.length && (p.opacity === undefined || p.opacity >= 0.5)) {
      let r = 0, g = 0, bl = 0, a = 0; for (const s of p.gradientStops) { r += s.color.r; g += s.color.g; bl += s.color.b; a += s.color.a; }
      const k = p.gradientStops.length; if (a / k >= 0.5) return {r: r / k, g: g / k, b: bl / k}; } }
  return null; };
const bgOf = n => { const bb = n.absoluteBoundingBox; if (!bb) return {kind: 'light'};
  const cx = bb.x + bb.width / 2, cy = bb.y + bb.height / 2; let cur = n, g = 0, col = null;
  while (cur && cur.parent && g++ < 40) { const par = cur.parent;
    if ('children' in par) { const idx = par.children.indexOf(cur);
      for (let i = idx - 1; i >= 0; i--) { const s = par.children[i]; if (!s.visible || !s.absoluteBoundingBox) continue; const q = s.absoluteBoundingBox;
        if (cx >= q.x && cx <= q.x + q.width && cy >= q.y && cy <= q.y + q.height) { const f = solidOf(s); if (f) { col = f; break; } } } }
    if (col) break; const f = solidOf(par); if (f) { col = f; break; } cur = par; }
  if (col === 'img') return {kind: 'img'}; if (!col) return {kind: 'light'};
  const L = lab(col); if (L[0] < 45) return {kind: 'dark'};
  if (chroma(L) > 28 && L[1] < -20 && L[0] >= 55 && L[0] < 88) return {kind: 'brand'};
  return {kind: L[0] < 55 ? 'dark' : 'light'}; };
// text colour: role by lightness for neutrals (chroma under 22), nearest status role otherwise; on-brand text on a brand fill
const TR = CONFIG.textRoles;
const pickText = (c, bg) => { const L = lab(c), ch = chroma(L), l = L[0];
  if (bg.kind === 'brand') return {k: TR.onBrand, fix: true};
  if (bg.kind === 'dark' || bg.kind === 'img') return ch < 22 && l >= 78 ? {k: TR.inverse} : null;
  if (ch < 22) { if (l < 32) return {k: TR.primary}; if (l <= 80) return {k: TR.secondary}; if (l >= 93) return {k: TR.inverse}; return null; }
  let best = null; for (const k of TR.chromatic) { if (!V[k]) continue; const d = dE(L, lab(resolveVal(V[k]))); if (!best || d < best.d) best = {k, d}; }
  return best && best.d <= 25 ? best : null; };
// paints: bind first, set opacity in a second assignment (a bound paint passed with opacity resets to 100%)
const opOf = p => p.opacity === undefined ? 1 : p.opacity;
const isBound = p => p.boundVariables && p.boundVariables.color;
const bindPaint = (orig, key) => { const p = figma.variables.setBoundVariableForPaint({type: 'SOLID', color: {r: orig.color.r, g: orig.color.g, b: orig.color.b}}, 'color', V[key]);
  const q = {...p}; if (orig.blendMode) q.blendMode = orig.blendMode; if (orig.visible === false) q.visible = false; return q; };
const setPaints = (n, key, paints, ops) => { n[key] = paints; if (ops.some(o => o < 1)) { const cl = JSON.parse(JSON.stringify(n[key])); cl.forEach((p, i) => { if (ops[i] !== undefined && ops[i] < 1) p.opacity = ops[i]; }); n[key] = cl; } };
