"""Essence word -> design levers. A starting suggestion the designer accepts, edits or rejects."""

LEVERS = {
    "premium": {"color": "restrained: neutrals carry the page, brand color rare and deep",
                "type": "lighter weights, generous tracking, refined serif or neo-grotesque",
                "shape": "small radii, crisp edges", "density": "spacious",
                "elevation": "subtle, soft shadows"},
    "playful": {"color": "high coverage, saturated brand color, warm neutrals",
                "type": "rounded humanist faces, heavy headings",
                "shape": "large radii, pill buttons", "density": "comfortable",
                "elevation": "flat with color blocking"},
    "energetic": {"color": "high saturation, bold contrast against dark text",
                  "type": "heavy weights, tight line height in headings",
                  "shape": "medium to large radii", "density": "compact to comfortable",
                  "elevation": "flat, sharp offsets"},
    "cheerful": {"color": "warm, light brand color used generously; dark text on it",
                 "type": "friendly rounded sans, medium body weight",
                 "shape": "large radii", "density": "comfortable", "elevation": "flat"},
    "trustworthy": {"color": "cool blues and greens, neutral-dominant", "type": "neutral sans, regular weights",
                    "shape": "medium radii", "density": "comfortable", "elevation": "subtle"},
    "calm": {"color": "low saturation, wide neutral range", "type": "light to regular weights, open leading",
             "shape": "medium to large radii", "density": "spacious", "elevation": "very soft"},
    "bold": {"color": "full-strength brand color, strong dark neutrals", "type": "heavy headings, large scale",
             "shape": "either sharp or pill, never mid", "density": "comfortable", "elevation": "flat or hard shadow"},
    "minimal": {"color": "near-monochrome, one accent", "type": "single family, few weights",
                "shape": "small radii", "density": "spacious", "elevation": "none"},
    "friendly": {"color": "warm accents, soft neutrals", "type": "rounded or humanist sans",
                 "shape": "large radii", "density": "comfortable", "elevation": "soft"},
    "technical": {"color": "cool neutrals, status colors prominent", "type": "grotesque plus mono for data",
                  "shape": "small radii", "density": "compact", "elevation": "borders over shadows"},
    "warm": {"color": "warm neutrals (stone, sand), earthy brand color", "type": "humanist or serif headings",
             "shape": "medium radii", "density": "comfortable", "elevation": "soft"},
    "snackable": {"color": "bright, high coverage", "type": "short, heavy headings, rounded sans",
                  "shape": "large radii", "density": "compact", "elevation": "flat"},
}
